server:
  port: 2333

lavalink:
  server:
    password: "youshallnotpass"
    sources:
      youtube: true
      spotify: true
      soundcloud: true
      bandcamp: true
      twitch: true
      vimeo: true
      http: true
      local: false
